// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2E7zn4PZLaz1p7nTJzU1_k2nRN0-2g0w',
    appId: '1:318890344695:web:ad29dc50cb47bf44de13f2',
    messagingSenderId: '318890344695',
    projectId: 'act15-52c2b',
    authDomain: 'act15-52c2b.firebaseapp.com',
    storageBucket: 'act15-52c2b.firebasestorage.app',
    measurementId: 'G-FGRT2X13PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWNXZGvYa7CQfnonr7aq9gOczJPoPF2CY',
    appId: '1:318890344695:android:5ff43aa53ecc5c98de13f2',
    messagingSenderId: '318890344695',
    projectId: 'act15-52c2b',
    storageBucket: 'act15-52c2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdaYuNrhSjnDvRTj0FSdfv0vFVEqCxpv4',
    appId: '1:318890344695:ios:83359489b5f68e3dde13f2',
    messagingSenderId: '318890344695',
    projectId: 'act15-52c2b',
    storageBucket: 'act15-52c2b.firebasestorage.app',
    iosBundleId: 'com.example.act15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdaYuNrhSjnDvRTj0FSdfv0vFVEqCxpv4',
    appId: '1:318890344695:ios:83359489b5f68e3dde13f2',
    messagingSenderId: '318890344695',
    projectId: 'act15-52c2b',
    storageBucket: 'act15-52c2b.firebasestorage.app',
    iosBundleId: 'com.example.act15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2E7zn4PZLaz1p7nTJzU1_k2nRN0-2g0w',
    appId: '1:318890344695:web:bb20db4fc750651dde13f2',
    messagingSenderId: '318890344695',
    projectId: 'act15-52c2b',
    authDomain: 'act15-52c2b.firebaseapp.com',
    storageBucket: 'act15-52c2b.firebasestorage.app',
    measurementId: 'G-XF5W84S4TJ',
  );
}
